---
# Allows me to control an Apple TV (3rd and 4th generation)
#
# https://www.home-assistant.io/components/apple_tv/
#
apple_tv:
  - host: !secret apple_tv_livingroom_host
    login_id: !secret apple_tv_livingroom_login_id
    name: Livingroom AppleTV
    start_off: true
