---
# Light group: Livingroom Computer lights
# My computer / workspace is in the livingroom, these lights are around
# this area, allowing me to control these separately.
#
# https://www.home-assistant.io/components/light.group/
#
platform: group
name: livingroom_computer_corner
entities:
  - light.livingroom_window_1
  - light.livingroom_window_2
