---
# Provides a list of entities to include in HomeKit.
#
# https://www.home-assistant.io/components/homekit/#include_entities
#
include_entities:
  - climate.bedroom_master_thermostat
  - climate.toon_van_eneco
  - light.bedroom_master_bedside
  - light.bedroom_master_ceiling
  - light.kitchen_ceiling
  - light.kitchen_cupboard
  - light.livingroom_bar
  - light.livingroom_computer_corner
  - light.livingroom_desk
  - light.livingroom_spotlight
  - light.livingroom_tv
  - light.livingroom_window
