---
# Light group: Livingroom: All
# Groups together all Livingroom lights for quick and easy switching
#
# https://www.home-assistant.io/components/light.group/
#
- platform: group
  name: All livingroom
  entities:
    - light.livingroom_window_1
    - light.livingroom_window_2
    - light.livingroom_window_3
    - light.livingroom_window_4
    - light.livingroom_window_5
    - light.livingroom_window_6
    - light.livingroom_window_7
    - light.livingroom_spotlight
