---
# Light group: Livingroom Window
# My livingroom window is 10 meters long and has 7 Ikea Tradfri GU10 WS (400lm)
# spots and I want them to act as one.
#
# https://www.home-assistant.io/components/light.group/
#
- platform: group
  name: Livingroom window
  entities:
    - light.livingroom_window_1
    - light.livingroom_window_2
    - light.livingroom_window_3
    - light.livingroom_window_4
    - light.livingroom_window_5
    - light.livingroom_window_6
    - light.livingroom_window_7
