---
- platform: yeelight
  devices:
    !secret light_yeelight_bedroom_master_daphne:
      name: Master Bedroom Bedside Daphne
      transition: 1000
      use_music_mode: True
      save_on_change: False
