---
# Adds an iframe panel to the Home Assistant frontend for the Octobox add-on.
# This allows me to access Octobox straight from Home Asssitant's UI
#
# https://github.com/hassio-addons/addon-octobox#embedding-into-home-assistant
# https://www.home-assistant.io/components/panel_iframe/
#
octobox:
  title: Octobox
  icon: mdi:github-face
  url: !secret panel_iframe_octobox_url
