---
#
# Customizes the PIR sensor installed in the restroom
#
# https://www.home-assistant.io/docs/configuration/customizing-devices/
# https://www.home-assistant.io/components/binary_sensor/
#

# Changes the device class of the binary sensor
# and ads a nice icon to it :)
binary_sensor.pir_toilet:
  device_class: occupancy
