---
# I run the Pi-hole add-on on my Hassio installation
# This allows me to block ads network wide and enhance privacy as well.
#
# This sensor fetches information about the current status of Pi-hole.
# While not really useful, I can push them to InfluxDB that allows me
# to see trends over time.
#
# https://github.com/hassio-addons/addon-pi-hole
# https://www.home-assistant.io/components/sensor.pi_hole/
#

##
# The sensor is currently disabled due to a bug
# https://github.com/home-assistant/home-assistant/issues/16810
##

# - platform: pi_hole
#   host: localhost:4865
#   location: admin

#   # My Pi-hole has SSL enabled
#   ssl: true

#   # My Pi-hole uses a different domain for the SSL, so I have to turn this off.
#   verify_ssl: false

#   # The list below is actually every single value you can get from Pi-hole.
#   monitored_conditions:
#     - ads_blocked_today
#     - ads_percentage_today
#     - dns_queries_today
#     - domains_being_blocked
#     - queries_cached
#     - queries_forwarded
#     - unique_clients
#     - unique_domains
#     - unique_domains
