---
# Provides a list of entities to include in Google Assistant.
#
# https://www.nabucasa.com/config/google_assistant
#
include_entities:
  - climate.toon_van_eneco
  - light.kitchen_ceiling
  - light.kitchen_cupboard
  - light.livingroom_bar
  - light.livingroom_computer_corner
  - light.livingroom_desk
  - light.livingroom_spotlight
  - light.livingroom_window
