---
# My cupboard lights are connected using a z-wave wall switch.
# This makes the device a "switch" withing Home Assistant and therefore
# it shows up as a switch in HomeKit and Google Assistant as well.
#
# This little light template mimics the behavior of the switch.
#
# https://www.home-assistant.io/components/light.template/
#
platform: template
lights:
  kitchen_cupboard:
    friendly_name: "Keukenkast"
    entity_id: switch.kitchen_cupboard
    value_template: "{{ is_state('switch.kitchen_cupboard', 'on') }}"
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.kitchen_cupboard
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.kitchen_cupboard
