---
alias: Turn Toilet lights on when motion is detected
trigger:
  platform: state
  entity_id: binary_sensor.toilet_motion
  to: 'on'
action:
  service: light.turn_on
  data:
    transition: 2
    brightness: 50
    entity_id:
      - light.toilet
