---
# Groups all my livingroom lights
#
# The weird exception here is the `light.kitchenbar`. This light faces the
# living, so it makes actually more sense to add it in here.
#
# https://www.home-assistant.io/components/group/
#
livingroom_lights:
  name: Livingroom Lights
  entities:
    - light.livingroom_window
    - light.livingroom_spotlight
    - light.livingroom_computer_corner
    - light.kitchen_bar
