---
homeassistant:
  # Name of this Home Assistant instance... I've tried to be original... ;)
  name: Home
  
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation
  
  # metric for Metric, imperial for Imperial
  unit_system: metric
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  
  # Load packages (split-configuration format)
  packages: !include_dir_named components

# The following are loaded from directories
automation: !include_dir_merge_list automations
device_tracker: !include_dir_merge_list device_trackers
group: !include_dir_merge_named groups
# input_boolean: !include_dir_merge_named input_booleans
media_player: !include_dir_merge_list media_players
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
tts: !include_dir_merge_list tts
