---
resources:
  - !include lovelace/resources/mini_media_player.yaml
  - !include lovelace/resources/slider_entity_row.yaml

title: Home Control Panel
views:
  - !include lovelace/views/downstairs.yaml
  - !include lovelace/views/upstairs.yaml
  - !include lovelace/views/outside.yaml
  - !include lovelace/views/security.yaml
