---
# This automation turns on the ceiling light in our entrance
# as soon as there is movement detected.
#
alias: entrance_motion_lights_on
trigger:
  platform: state
  entity_id: binary_sensor.entrance_motion
  to: 'on'
action:
  service: light.turn_on
  data:
    transition: 3
    brightness: 45
    color_temp: 395
    entity_id:
      - light.entrance_ceiling
