---
alias: livingroom_theater_lights_off
initial_state: true
trigger:
  - platform: state
    entity_id: media_player.livingroom_shield
    to: 'off'
action:
  service: light.turn_off
  entity_id:
    - light.livingroom_tv
