---
id: upstairs
title: Boven
icon: mdi:stairs
cards:
  - !include ../cards/compact_custom_header.yaml
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.bedroom_master_ceiling
          - type: light
            entity: light.bedroom_master_bedside
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.bedroom_master_bedside_frenck
          - type: light
            entity: light.bedroom_master_bedside_daphne
  - type: horizontal-stack
    cards:
      - type: glance
        title: Badkamer
        show_name: false
        entities:
          - sensor.bathroom_temperature
          - sensor.bathroom_humidity
      - type: light
        entity: light.bathroom_ceiling
        name: Plafond
  - type: entities
    tile: Upstrairs
    entities:
      - light.landing_ceiling

  - type: custom:mini-graph-card
    entities: sensor.lilly_thermostat_temperature
    location_icon: left
    location_state: center
    show:
      fill: false
      extrema: true
    height: 75
    animate: true
    hour24: true
    line_color: var(--primary-color)
    line_color_above:
      - value: 19
        color: red
    line_color_below:
      - value: 15
        color: white
  - type: custom:popup-card
    entity: sensor.lilly_thermostat_temperature
    title: Thermostaat Lilly
    card:
      type: thermostat
      entity: climate.bedroom_lilly_thermostat

  - type: custom:mini-graph-card
    entities: sensor.flynn_thermostat_temperature
    location_icon: left
    location_state: center
    show:
      fill: false
      extrema: true
    height: 75
    animate: true
    hour24: true
    line_color: var(--primary-color)
    line_color_above:
      - value: 19
        color: red
    line_color_below:
      - value: 15
        color: white
  - type: custom:popup-card
    entity: sensor.flynn_thermostat_temperature
    title: Thermostaat Flynn
    card:
      type: thermostat
      entity: climate.bedroom_flynn_thermostat

  - type: custom:mini-graph-card
    entities: sensor.bedroom_master_thermostat_temperature
    location_icon: left
    location_state: center
    show:
      fill: false
      extrema: true
    height: 75
    animate: true
    hour24: true
    line_color: var(--primary-color)
    line_color_above:
      - value: 20
        color: red
    line_color_below:
      - value: 15
        color: white
  - type: custom:popup-card
    entity: sensor.bedroom_master_thermostat_temperature
    title: Thermostaat Masterbedroom
    card:
      type: thermostat
      entity: climate.bedroom_master_thermostat
