---
id: upstairs
title: Boven
icon: mdi:stairs
cards:
  - type: custom:simple-thermostat
    entity: climate.bedroom_master_thermostat
    hide:
      mode: true
      state: true
    sensors:
      - entity: binary_sensor.slaapkamer_raam
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.bedroom_master_ceiling
          - type: light
            entity: light.bedroom_master_bedside
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.bedroom_master_bedside_frenck
          - type: light
            entity: light.bedroom_master_bedside_daphne
  - type: horizontal-stack
    cards:
      - type: glance
        title: Badkamer
        show_name: false
        entities:
          - sensor.bathroom_temperature
          - sensor.bathroom_humidity
      - type: light
        entity: light.bathroom_ceiling
        name: Plafond
  - type: entities
    tile: Upstrairs
    entities:
      - light.landing_ceiling
  - type: custom:simple-thermostat
    entity: climate.bedroom_flynn_thermostat
    hide:
      mode: true
      state: true
    sensors:
      - entity: binary_sensor.bedroom_flynn_window
  - type: custom:simple-thermostat
    entity: climate.bedroom_lilly_thermostat
    hide:
      mode: true
      state: true
