---
# When the alarm gets armed away...
# Turn down the heating, lights and other devices.
#
# This automation essentially extends the `alarm_armed` automation.
#
alias: house_alarm_armed_away
initial_state: true
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.toon_van_eneco
      temperature: 16
  - service: light.turn_off
    data:
      entity_id:
        - light.bathroom_ceiling
        - light.bedroom_master_bedside_daphne
        - light.bedroom_master_bedside_frenck
        - light.bedroom_master_ceiling
