---
alias: Turn Entrance lights off when no motion is detected
trigger:
  platform: state
  entity_id: binary_sensor.entrance_motion
  to: 'off'
  for:
    seconds: 10
action:
  service: light.turn_off
  data:
    transition: 15
    entity_id: light.entrance_ceiling
