---
# My desk light is connected using a z-wave wall switch.
# This makes the device a "switch" withing Home Assistant and therefore
# it shows up as a switch in HomeKit and Google Assistant as well.
#
# This little light template mimics the behavior of the switch.
#
# https://www.home-assistant.io/components/light.template/
#
platform: template
lights:
  livingroom_desk:
    friendly_name: "Bureaulamp"
    entity_id: switch.livingroom_desk
    value_template: "{{ is_state('switch.livingroom_desk', 'on') }}"
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.livingroom_desk
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.livingroom_desk
